name: Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t anontech27/quizit-backend:latest .
      - name: Publish image to Docker Hub
        run: docker push anontech27/quizit-backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Upload .env to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} .env ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/quizit-backend/.env
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            docker pull anontech27/quizit-backend:latest
            docker rm -f quizit-backend-container || true
            docker run -d -p 5000:5000 \
              --name quizit-backend-container \
              --env-file /home/ubuntu/quizit-backend .env \
              anontech27/quizit-backend:latest
          EOF
