name: Deploy to EC2

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t quizappimage/quizit .
      - name: Publish image to docker hub
        run: docker push quizappimage/quizit:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            docker pull quizappimage/quizit:latest
            docker rm -f quizit-container || true
            docker run -d -p 5000:5000 --name quizit-container quizappimage/quizit:latest
          EOF
