name: Keep Render Server Awake

on:
  workflow_dispatch:
  schedule:
    - cron: "*/12 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server
        run: curl https://quizit-master-1.onrender.com/graphql
